name: DevSecOps IaC Security Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  checkov-scan:
    name: Checkov Policy-as-Code Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Run Checkov IaC Scanner
        uses: bridgecrewio/checkov-action@master
        with:
          framework: terraform
          output_format: cli
          soft_fail: true
          skip_check: CKV_AWS_18,CKV_AWS_21,CKV_AWS_35,CKV_AWS_274,CKV2_AWS_61,CKV2_AWS_62

  terraform-validate:
    name: Terraform Validate
    needs: checkov-scan
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::487739920436:role/github-actions-zero-trust-role
          aws-region: us-east-1

      - name: Terraform Init & Validate
        run: |
          terraform init -backend=false
          terraform validate